[package]
name = "mailgun"
version = "0.1.0"
authors = ["Bram Vandenbogaerde <bram.vandenbogaerde@gmail.com>"]

[dependencies]
serde_derive = "1.0.27"
serde = "1.0.27"
reqwest = "0.8.3"
handlebars = "0.30.0"
